spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: true

  datasource:
    url: jdbc:postgresql://database-1.cvyhsoweumof.eu-central-1.rds.amazonaws.com/postgres
    username: postgres
    password: postgres

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

