spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://database-1.cvyhsoweumof.eu-central-1.rds.amazonaws.com/postgres
    username: postgres
    password: postgres

